# -*- coding: utf-8 -*-
"""perceptron-demo.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1QUH6Sj_hBrKproJCor5_SX_I3AuHIdCO
"""

import numpy as np
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt

df = pd.read_csv('/content/placement.csv')

print(df.shape)
df.head()

sns.scatterplot(x=df['cgpa'], y=df['resume_score'], hue=df['placed'])

X = df.iloc[:,0:2]
y = df.iloc[:,-1]

from sklearn.linear_model import Perceptron
p = Perceptron()

p.fit(X,y)

p.coef_

p.intercept_

from mlxtend.plotting import plot_decision_regions

plot_decision_regions(X.values, y.values, clf=p, legend=2)